<?php

namespace Integracao\ControlPay\Constants;

/**
 * Class ControlPayParameterConst
 * @package Integracao\ControlPay\Constants
 */
class ControlPayParameterConst
{
    const CONTROLPAY_HOST = 'CONTROLPAY_HOST';
    const CONTROLPAY_USER = 'CONTROLPAY_USER';
    const CONTROLPAY_PWD = 'CONTROLPAY_PWD';
    const CONTROLPAY_KEY = 'CONTROLPAY_KEY';
    const CONTROLPAY_TIMEOUT = 'CONTROLPAY_TIMEOUT';
    const CONTROLPAY_OAUTH_TYPE = 'CONTROLPAY_OAUTH_TYPE';
    const CONTROLPAY_DEFAULT_PESSOA_ID = 'CONTROLPAY_DEFAULT_PESSOA_ID';
    const CONTROLPAY_DEFAULT_TERMINAL_ID = 'CONTROLPAY_DEFAULT_TERMINAL_ID';
    const CONTROLPAY_DEFAULT_PRODUTO_ID = 'CONTROLPAY_DEFAULT_PRODUTO_ID';
    const CONTROLPAY_DEFAULT_FORMA_PAGAMENTO_ID = 'CONTROLPAY_DEFAULT_FORMA_PAGAMENTO_ID';
    const CONTROLPAY_DEFAULT_FORMA_AGUARDA_TEF = 'CONTROLPAY_DEFAULT_FORMA_AGUARDA_TEF';
    const CONTROLPAY_DEFAULT_SENHA_TECNICA = 'CONTROLPAY_DEFAULT_SENHA_TECNICA';
}